CONFIG_LOG=y
CONFIG_GPIO=y
CONFIG_HAPTICS=y
CONFIG_HAPTICS_CS40L5X_ALT_OS=y
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y

CONFIG_HAPTICS_CS40L51=y
# CONFIG_HAPTICS_CS40L52 is not set
# CONFIG_HAPTICS_CS40L53 is not set