
/**
 * @file cs40l30_sym.h
 *
 * @brief Master table of known firmware symbols for the CS40L30 Driver module
 *
 * @copyright
 * Copyright (c) Cirrus Logic 2021 All Rights Reserved, http://www.cirrus.com/
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * firmware_converter.py version: 3.2.0
 * Command:  ..\..\tools\firmware_converter\firmware_converter.py fw_img_v2 cs40l30 Stumpy_RAM_Rev1.0.35.wmfw
 *
 *
 */

#ifndef CS40L30_SYM_H
#define CS40L30_SYM_H

#ifdef __cplusplus
extern "C" {
#endif

/***********************************************************************************************************************
 * LITERALS & CONSTANTS
 **********************************************************************************************************************/

/**
 * @defgroup CS40L30_ALGORITHMS
 * @brief Defines indicating presence of HALO Core Algorithms
 *
 * @{
 */
#define CS40L30_ALGORITHM_FIRMWARE_HAPTICS
#define CS40L30_ALGORITHM_VIBEGEN
#define CS40L30_ALGORITHM_API_STREAMING
#define CS40L30_ALGORITHM_GPIO
#define CS40L30_ALGORITHM_BUZZGEN
#define CS40L30_ALGORITHM_FORCE_SENSE
#define CS40L30_ALGORITHM_PM
#define CS40L30_ALGORITHM_EVENT_HANDLER
#define CS40L30_ALGORITHM_FORCE_SENSE_ACTIVE
#define CS40L30_ALGORITHM_SVC
/** @} */

/**
 * @defgroup CS40L30_SYM_
 * @brief Single source of truth for firmware symbols known to the driver.
 *
 * @{
 */
// FIRMWARE_HAPTICS
#define CS40L30_SYM_FIRMWARE_HAPTICS_SYSTEM_CONFIG_XM_STRUCT_T                  (0x1)
#define CS40L30_SYM_FIRMWARE_HAPTICS_HALO_STATE                                 (0x2)
#define CS40L30_SYM_FIRMWARE_HAPTICS_HALO_HEARTBEAT                             (0x3)
#define CS40L30_SYM_FIRMWARE_HAPTICS_POWER_MODE                                 (0x4)
#define CS40L30_SYM_FIRMWARE_HAPTICS_AUDIO_BLK_SIZE                             (0x5)
#define CS40L30_SYM_FIRMWARE_HAPTICS_USER_CONTROL_INPUT                         (0x6)
#define CS40L30_SYM_FIRMWARE_HAPTICS_USER_CONTROL_RESPONSE                      (0x7)
#define CS40L30_SYM_FIRMWARE_HAPTICS_HW_WATCHDOG_ENABLE_OTP                     (0x8)
#define CS40L30_SYM_FIRMWARE_HAPTICS_FORCE_WATCHDOG                             (0x9)
#define CS40L30_SYM_FIRMWARE_HAPTICS_POTP_MEM_CONF                              (0xa)
#define CS40L30_SYM_FIRMWARE_HAPTICS_POTP_MEM_CALIB                             (0xb)
#define CS40L30_SYM_FIRMWARE_HAPTICS_FIRST_BOOT_EN                              (0xc)
#define CS40L30_SYM_FIRMWARE_HAPTICS_CLOCK_STRETCH_EN                           (0xd)
#define CS40L30_SYM_FIRMWARE_HAPTICS_SYSTEM_CONFIG_YM_STRUCT_T                  (0xe)
#define CS40L30_SYM_FIRMWARE_HAPTICS_TUNING_FLAGS                               (0xf)
// VIBEGEN
#define CS40L30_SYM_VIBEGEN_VIBEGEN_XM_STRUCT_T                                 (0x10)
#define CS40L30_SYM_VIBEGEN_F0_OTP_STORED                                       (0x11)
#define CS40L30_SYM_VIBEGEN_REDC_OTP_STORED                                     (0x12)
#define CS40L30_SYM_VIBEGEN_F0_OFFSET                                           (0x13)
#define CS40L30_SYM_VIBEGEN_TIMEOUT_MS                                          (0x14)
#define CS40L30_SYM_VIBEGEN_TRIGGER_WAVE_INDEX                                  (0x15)
#define CS40L30_SYM_VIBEGEN_END_PLAYBACK                                        (0x16)
#define CS40L30_SYM_VIBEGEN_NUM_OF_WAVES                                        (0x17)
#define CS40L30_SYM_VIBEGEN_WAVE_TYPE                                           (0x18)
#define CS40L30_SYM_VIBEGEN_PLAY_STATE                                          (0x19)
#define CS40L30_SYM_VIBEGEN_EVENT_COUNT                                         (0x1a)
#define CS40L30_SYM_VIBEGEN_Q_STORED                                            (0x1b)
#define CS40L30_SYM_VIBEGEN_P_VIBEGEN_ROM                                       (0x1c)
#define CS40L30_SYM_VIBEGEN_COMPENSATION_ENABLE                                 (0x1d)
#define CS40L30_SYM_VIBEGEN_WAVE_XM_TABLE                                       (0x1e)
#define CS40L30_SYM_VIBEGEN_VIBEGEN_YM_STRUCT_T                                 (0x1f)
#define CS40L30_SYM_VIBEGEN_WAVE_YM_TABLE                                       (0x20)
// API_STREAMING
#define CS40L30_SYM_API_STREAMING_API_STREAMING_XM_STRUCT_T                     (0x21)
#define CS40L30_SYM_API_STREAMING_STREAM_START                                  (0x22)
#define CS40L30_SYM_API_STREAMING_RX_READY                                      (0x23)
#define CS40L30_SYM_API_STREAMING_RX_BUFFER_LENGTH                              (0x24)
#define CS40L30_SYM_API_STREAMING_RX_CHANNEL_ID                                 (0x25)
#define CS40L30_SYM_API_STREAMING_STATUS                                        (0x26)
#define CS40L30_SYM_API_STREAMING_OVERRUN_COUNTER                               (0x27)
#define CS40L30_SYM_API_STREAMING_API_STREAMING_YM_STRUCT_T                     (0x28)
#define CS40L30_SYM_API_STREAMING_PING_BUFFER_STATUS                            (0x29)
#define CS40L30_SYM_API_STREAMING_PONG_BUFFER_STATUS                            (0x2a)
#define CS40L30_SYM_API_STREAMING_BUFFER_SAMPLE_COUNTER                         (0x2b)
#define CS40L30_SYM_API_STREAMING_UP_TIME_STAMP_MSEC                            (0x2c)
#define CS40L30_SYM_API_STREAMING_DN_TIME_STAMP_MSEC                            (0x2d)
#define CS40L30_SYM_API_STREAMING_DATA_TIME_STAMP_MSEC                          (0x2e)
#define CS40L30_SYM_API_STREAMING_PRIVATE_RX_CHAN_ID                            (0x2f)
#define CS40L30_SYM_API_STREAMING_RESERVED_BUFFER                               (0x30)
#define CS40L30_SYM_API_STREAMING_RESERVED_DATA_SIZE                            (0x31)
#define CS40L30_SYM_API_STREAMING_PING_BUFFER                                   (0x32)
#define CS40L30_SYM_API_STREAMING_PONG_BUFFER                                   (0x33)
#define CS40L30_SYM_API_STREAMING_PRIVATE_RX_BUFFER_LENGTH                      (0x34)
#define CS40L30_SYM_API_STREAMING_STREAM_FIRST_START_FLAG                       (0x35)
// GPIO
#define CS40L30_SYM_GPIO_GPIO_XM_STRUCT_T                                       (0x36)
#define CS40L30_SYM_GPIO_GPIO_INTERRUPT_COUNTER                                 (0x37)
#define CS40L30_SYM_GPIO_GPI_ENABLE_BITMASK                                     (0x38)
#define CS40L30_SYM_GPIO_GPO_ENABLE_BITMASK                                     (0x39)
#define CS40L30_SYM_GPIO_SUP_GPI_COUNT                                          (0x3a)
#define CS40L30_SYM_GPIO_SUP_GPI                                                (0x3b)
// BUZZGEN
#define CS40L30_SYM_BUZZGEN_BUZZGEN_XM_STRUCT_T                                 (0x3c)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS1_BUZZ_FREQ                             (0x3d)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS1_BUZZ_LEVEL                            (0x3e)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS1_BUZZ_DURATION                         (0x3f)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS2_BUZZ_FREQ                             (0x40)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS2_BUZZ_LEVEL                            (0x41)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS2_BUZZ_DURATION                         (0x42)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS3_BUZZ_FREQ                             (0x43)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS3_BUZZ_LEVEL                            (0x44)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS3_BUZZ_DURATION                         (0x45)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS4_BUZZ_FREQ                             (0x46)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS4_BUZZ_LEVEL                            (0x47)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS4_BUZZ_DURATION                         (0x48)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS5_BUZZ_FREQ                             (0x49)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS5_BUZZ_LEVEL                            (0x4a)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS5_BUZZ_DURATION                         (0x4b)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS6_BUZZ_FREQ                             (0x4c)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS6_BUZZ_LEVEL                            (0x4d)
#define CS40L30_SYM_BUZZGEN_BUZZ_EFFECTS6_BUZZ_DURATION                         (0x4e)
#define CS40L30_SYM_BUZZGEN_TRIGGER_BUZZ                                        (0x4f)
// FORCE_SENSE
#define CS40L30_SYM_FORCE_SENSE_FSENSE_XM_STRUCT_T                              (0x50)
#define CS40L30_SYM_FORCE_SENSE_NUM_SENSORS                                     (0x51)
#define CS40L30_SYM_FORCE_SENSE_POLARITY_REVERSALS                              (0x52)
#define CS40L30_SYM_FORCE_SENSE_MAX_CORRELATION                                 (0x53)
#define CS40L30_SYM_FORCE_SENSE_TEMPERATURE_COMP_T0                             (0x54)
#define CS40L30_SYM_FORCE_SENSE_CALIB_DIGITAL_GAIN                              (0x55)
#define CS40L30_SYM_FORCE_SENSE_CALIB_ANALOG_GAIN                               (0x56)
#define CS40L30_SYM_FORCE_SENSE_MAX_GAIN                                        (0x57)
#define CS40L30_SYM_FORCE_SENSE_CALIB_FSENSE_SCALING                            (0x58)
#define CS40L30_SYM_FORCE_SENSE_TEMPERATURE_COMP_SLOPES                         (0x59)
#define CS40L30_SYM_FORCE_SENSE_TEMPERATURE_COMP_LRA_TIMEOUT                    (0x5a)
#define CS40L30_SYM_FORCE_SENSE_TEMPERATURE_COMP_MIN_TEMPERATURE                (0x5b)
#define CS40L30_SYM_FORCE_SENSE_TEMPERATURE_COMP_MAX_TEMPERATURE                (0x5c)
#define CS40L30_SYM_FORCE_SENSE_VBATT_FACTOR_LOW_POWER                          (0x5d)
#define CS40L30_SYM_FORCE_SENSE_EMI_FACTOR_LRA_ACTIVE                           (0x5e)
#define CS40L30_SYM_FORCE_SENSE_EMI_FACTOR_LRA_INACTIVE                         (0x5f)
#define CS40L30_SYM_FORCE_SENSE_LONG_PRESS_MIN                                  (0x60)
#define CS40L30_SYM_FORCE_SENSE_LONG_PRESS_MAX                                  (0x61)
#define CS40L30_SYM_FORCE_SENSE_RISE_TH_NEWTONS                                 (0x62)
#define CS40L30_SYM_FORCE_SENSE_FALL_TH_NEWTONS                                 (0x63)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_ALPHA                                  (0x64)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_LAMBDA                                 (0x65)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_ACTIVITY_TIMEOUT                       (0x66)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_DRIFT_MAX_LIM                          (0x67)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_DRIFT_TIMEOUT                          (0x68)
#define CS40L30_SYM_FORCE_SENSE_MIN_SIGNAL_TH_NEWTONS                           (0x69)
#define CS40L30_SYM_FORCE_SENSE_ACTIVITY_TIMEOUT                                (0x6a)
#define CS40L30_SYM_FORCE_SENSE_MINIMUM_SIGNAL_LEVEL_TIMEOUT                    (0x6b)
#define CS40L30_SYM_FORCE_SENSE_ALPHA_ANOMALY_DETECT                            (0x6c)
#define CS40L30_SYM_FORCE_SENSE_SENSOR_USED_ANOMALY_DET                         (0x6d)
#define CS40L30_SYM_FORCE_SENSE_ALPHA_CORR_FS1                                  (0x6e)
#define CS40L30_SYM_FORCE_SENSE_SENSORS_USED_CORR                               (0x6f)
#define CS40L30_SYM_FORCE_SENSE_ANOMALY_DETECT_PARAMS                           (0x70)
#define CS40L30_SYM_FORCE_SENSE_SENSORS_USED_NORM                               (0x71)
#define CS40L30_SYM_FORCE_SENSE_NUM_VIRTUAL_BUTTONS                             (0x72)
#define CS40L30_SYM_FORCE_SENSE_SENSOR_2_BUTTON_MASK                            (0x73)
#define CS40L30_SYM_FORCE_SENSE_SENSOR_2_BUTTON_MAPPING                         (0x74)
#define CS40L30_SYM_FORCE_SENSE_BASE_RATE                                       (0x75)
#define CS40L30_SYM_FORCE_SENSE_BOOT_RATE                                       (0x76)
#define CS40L30_SYM_FORCE_SENSE_BOOT_TIME                                       (0x77)
#define CS40L30_SYM_FORCE_SENSE_TEMP_MON_PARAMS_REFRESH_RATE                    (0x78)
#define CS40L30_SYM_FORCE_SENSE_FSENSE_SAMPLE_COUNT                             (0x79)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_ONE                                    (0x7a)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_TWO                                    (0x7b)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_THREE                                  (0x7c)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_FOUR                                   (0x7d)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_5                                      (0x7e)
#define CS40L30_SYM_FORCE_SENSE_BASELINE_6                                      (0x7f)
#define CS40L30_SYM_FORCE_SENSE_RECURSIVE_FILTER_1OUT                           (0x80)
#define CS40L30_SYM_FORCE_SENSE_RECURSIVE_FILTER_2OUT                           (0x81)
#define CS40L30_SYM_FORCE_SENSE_RECURSIVE_FILTER_3OUT                           (0x82)
#define CS40L30_SYM_FORCE_SENSE_RECURSIVE_FILTER_4OUT                           (0x83)
#define CS40L30_SYM_FORCE_SENSE_RECURSIVE_FILTER_5OUT                           (0x84)
#define CS40L30_SYM_FORCE_SENSE_RECURSIVE_FILTER_6OUT                           (0x85)
#define CS40L30_SYM_FORCE_SENSE_VIRTUAL_BUTTON_ONE                              (0x86)
#define CS40L30_SYM_FORCE_SENSE_VIRTUAL_BUTTON_TWO                              (0x87)
#define CS40L30_SYM_FORCE_SENSE_VIRTUAL_BUTTON_THREE                            (0x88)
#define CS40L30_SYM_FORCE_SENSE_RISE_FLAG                                       (0x89)
#define CS40L30_SYM_FORCE_SENSE_FALL_FLAG                                       (0x8a)
#define CS40L30_SYM_FORCE_SENSE_BUTTON_STATES                                   (0x8b)
#define CS40L30_SYM_FORCE_SENSE_RECAL_REQUESTS                                  (0x8c)
#define CS40L30_SYM_FORCE_SENSE_COUNTER_ACTIVITY_TIMEOUT                        (0x8d)
#define CS40L30_SYM_FORCE_SENSE_COUNTER_BASELINE_DRIFT                          (0x8e)
#define CS40L30_SYM_FORCE_SENSE_COUNTER_LOW_SIGNAL                              (0x8f)
#define CS40L30_SYM_FORCE_SENSE_BOOT_TIME_COUNTER                               (0x90)
#define CS40L30_SYM_FORCE_SENSE_BOOT_RATE_MODE_ACTIVE                           (0x91)
#define CS40L30_SYM_FORCE_SENSE_FSAC_ROUTE                                      (0x92)
#define CS40L30_SYM_FORCE_SENSE_VDD_LOW_DB                                      (0x93)
#define CS40L30_SYM_FORCE_SENSE_INPUT1_NEWTONS                                  (0x94)
#define CS40L30_SYM_FORCE_SENSE_INPUT2_NEWTONS                                  (0x95)
#define CS40L30_SYM_FORCE_SENSE_INPUT3_NEWTONS                                  (0x96)
#define CS40L30_SYM_FORCE_SENSE_INPUT4_NEWTONS                                  (0x97)
#define CS40L30_SYM_FORCE_SENSE_INPUT5_NEWTONS                                  (0x98)
#define CS40L30_SYM_FORCE_SENSE_INPUT6_NEWTONS                                  (0x99)
#define CS40L30_SYM_FORCE_SENSE_ANOMALY_DET_STATE_ANOMALY_FEATURES              (0x9a)
#define CS40L30_SYM_FORCE_SENSE_ANOMALY_DET_STATE_ANOMALY_DETECTION_FLAG        (0x9b)
#define CS40L30_SYM_FORCE_SENSE_ANOMALY_DET_STATE_ANOMALY_DETECTION_CORR_SUM    (0x9c)
#define CS40L30_SYM_FORCE_SENSE_ANOMALY_DET_STATE_DISTANCE_TO_HYPERPLANE_DEBUG  (0x9d)
#define CS40L30_SYM_FORCE_SENSE_ANOMALY_DET_STATE_ALPHA_ANOMALY_DETECT_BOOTRATE (0x9e)
#define CS40L30_SYM_FORCE_SENSE_ANOMALY_DET_STATE_ALPHA_CORR_FS1_BOOTRATE       (0x9f)
#define CS40L30_SYM_FORCE_SENSE_TS_STATE_INCREMENT                              (0xa0)
#define CS40L30_SYM_FORCE_SENSE_BOOT_RATE_CLOCKSPEED                            (0xa1)
#define CS40L30_SYM_FORCE_SENSE_BASE_RATE_CLOCKSPEED                            (0xa2)
#define CS40L30_SYM_FORCE_SENSE_TEMP_MON_STATE_TEMPERATURE                      (0xa3)
#define CS40L30_SYM_FORCE_SENSE_TEMP_MON_STATE_UPDATE_COUNTER                   (0xa4)
// PM
#define CS40L30_SYM_PM_PM_XM_STRUCT_T                                           (0xa5)
#define CS40L30_SYM_PM_PM_TIMER_TIMEOUT_TICKS                                   (0xa6)
#define CS40L30_SYM_PM_PM_CUR_STATE                                             (0xa7)
#define CS40L30_SYM_PM_PM_TIMER_ENABLED                                         (0xa8)
#define CS40L30_SYM_PM_PM_STATE_LOCKS                                           (0xa9)
#define CS40L30_SYM_PM_POWER_ON_SEQUENCE                                        (0xaa)
// EVENT_HANDLER
#define CS40L30_SYM_EVENT_HANDLER_EVENT_HANDLER_XM_STRUCT_T                     (0xab)
#define CS40L30_SYM_EVENT_HANDLER_EVENT_MAP_TABLE_EVENT_DATA_PACKED             (0xac)
#define CS40L30_SYM_EVENT_HANDLER_EVENT_MAP_TABLE_INIT_FROM_OTP                 (0xad)
// FORCE_SENSE_ACTIVE
#define CS40L30_SYM_FORCE_SENSE_ACTIVE_FSENSE_ACTIVE_XM_STRUCT_T                (0xae)
#define CS40L30_SYM_FORCE_SENSE_ACTIVE_FSENSE_ACTIVE_YM_STRUCT_T                (0xaf)
// SVC
#define CS40L30_SYM_SVC_SVC_YM_STRUCT_T                                         (0xb0)
#define CS40L30_SYM_SVC_INIT_PH_PILOT_RU_STEP                                   (0xb1)
#define CS40L30_SYM_SVC_INIT_PH_PILOT_RD_STEP                                   (0xb2)
#define CS40L30_SYM_SVC_DEBUG_OUT_ENABLE                                        (0xb3)
#define CS40L30_SYM_SVC_DEBUG_OUT1_MUX                                          (0xb4)
#define CS40L30_SYM_SVC_DEBUG_OUT2_MUX                                          (0xb5)
#define CS40L30_SYM_SVC_LO_LP_SOS1_B0                                           (0xb6)
#define CS40L30_SYM_SVC_LO_LP_SOS1_B1                                           (0xb7)
#define CS40L30_SYM_SVC_LO_LP_SOS1_B2                                           (0xb8)
#define CS40L30_SYM_SVC_LO_LP_SOS1_A1                                           (0xb9)
#define CS40L30_SYM_SVC_LO_LP_SOS1_A2                                           (0xba)
#define CS40L30_SYM_SVC_LO_LP_SOS2_B0                                           (0xbb)
#define CS40L30_SYM_SVC_LO_LP_SOS2_B1                                           (0xbc)
#define CS40L30_SYM_SVC_LO_LP_SOS2_B2                                           (0xbd)
#define CS40L30_SYM_SVC_LO_LP_SOS2_A1                                           (0xbe)
#define CS40L30_SYM_SVC_LO_LP_SOS2_A2                                           (0xbf)
#define CS40L30_SYM_SVC_LO_LP_SOS3_B0                                           (0xc0)
#define CS40L30_SYM_SVC_LO_LP_SOS3_B1                                           (0xc1)
#define CS40L30_SYM_SVC_LO_LP_SOS3_B2                                           (0xc2)
#define CS40L30_SYM_SVC_LO_LP_SOS3_A1                                           (0xc3)
#define CS40L30_SYM_SVC_LO_LP_SOS3_A2                                           (0xc4)
#define CS40L30_SYM_SVC_LO_HP_SOS1_B0                                           (0xc5)
#define CS40L30_SYM_SVC_LO_HP_SOS1_B1                                           (0xc6)
#define CS40L30_SYM_SVC_LO_HP_SOS1_B2                                           (0xc7)
#define CS40L30_SYM_SVC_LO_HP_SOS1_A1                                           (0xc8)
#define CS40L30_SYM_SVC_LO_HP_SOS1_A2                                           (0xc9)
#define CS40L30_SYM_SVC_HI_BP_SOS1_B0                                           (0xca)
#define CS40L30_SYM_SVC_HI_BP_SOS1_B1                                           (0xcb)
#define CS40L30_SYM_SVC_HI_BP_SOS1_B2                                           (0xcc)
#define CS40L30_SYM_SVC_HI_BP_SOS1_A1                                           (0xcd)
#define CS40L30_SYM_SVC_HI_BP_SOS1_A2                                           (0xce)
#define CS40L30_SYM_SVC_HI_BP_SOS2_B0                                           (0xcf)
#define CS40L30_SYM_SVC_HI_BP_SOS2_B1                                           (0xd0)
#define CS40L30_SYM_SVC_HI_BP_SOS2_B2                                           (0xd1)
#define CS40L30_SYM_SVC_HI_BP_SOS2_A1                                           (0xd2)
#define CS40L30_SYM_SVC_HI_BP_SOS2_A2                                           (0xd3)
#define CS40L30_SYM_SVC_HI_BP_SOS3_B0                                           (0xd4)
#define CS40L30_SYM_SVC_HI_BP_SOS3_B1                                           (0xd5)
#define CS40L30_SYM_SVC_HI_BP_SOS3_B2                                           (0xd6)
#define CS40L30_SYM_SVC_HI_BP_SOS3_A1                                           (0xd7)
#define CS40L30_SYM_SVC_HI_BP_SOS3_A2                                           (0xd8)
#define CS40L30_SYM_SVC_HI_BP_SOS4_B0                                           (0xd9)
#define CS40L30_SYM_SVC_HI_BP_SOS4_B1                                           (0xda)
#define CS40L30_SYM_SVC_HI_BP_SOS4_B2                                           (0xdb)
#define CS40L30_SYM_SVC_HI_BP_SOS4_A1                                           (0xdc)
#define CS40L30_SYM_SVC_HI_BP_SOS4_A2                                           (0xdd)
#define CS40L30_SYM_SVC_V_GAIN                                                  (0xde)
#define CS40L30_SYM_SVC_I_GAIN                                                  (0xdf)
#define CS40L30_SYM_SVC_LO_V_GAIN                                               (0xe0)
#define CS40L30_SYM_SVC_LO_I_GAIN                                               (0xe1)
#define CS40L30_SYM_SVC_LO_DI_GAIN                                              (0xe2)
#define CS40L30_SYM_SVC_HI_V_GAIN                                               (0xe3)
#define CS40L30_SYM_SVC_HI_I_GAIN                                               (0xe4)
#define CS40L30_SYM_SVC_HI_DI_GAIN                                              (0xe5)
#define CS40L30_SYM_SVC_LO_DEN_MSB_THR                                          (0xe6)
#define CS40L30_SYM_SVC_HI_DEN_MSB_THR                                          (0xe7)
#define CS40L30_SYM_SVC_SW_EST_CONTROLS_HW                                      (0xe8)
#define CS40L30_SYM_SVC_REFLVL_CTRL                                             (0xe9)
#define CS40L30_SYM_SVC_RE_SF                                                   (0xea)
#define CS40L30_SYM_SVC_RE_HI_SF                                                (0xeb)
#define CS40L30_SYM_SVC_RE_LO_SF                                                (0xec)
#define CS40L30_SYM_SVC_RE_CAT_SF                                               (0xed)
#define CS40L30_SYM_SVC_RE_LO_STATUS                                            (0xee)
#define CS40L30_SYM_SVC_RE_HI_STATUS                                            (0xef)
#define CS40L30_SYM_SVC_RE_EST_STATUS                                           (0xf0)
#define CS40L30_SYM_SVC_VMON_OFFSET_STATUS                                      (0xf1)
#define CS40L30_SYM_SVC_IMON_OFFSET_STATUS                                      (0xf2)
#define CS40L30_SYM_SVC_RE_INIT_STATUS                                          (0xf3)
#define CS40L30_SYM_SVC_LE_EST_STATUS                                           (0xf4)
#define CS40L30_SYM_SVC_ERROR_STATUS                                            (0xf5)
#define CS40L30_SYM_SVC_HAPTIC_COMMAND                                          (0xf6)
#define CS40L30_SYM_SVC_MSG_HAPTICS_TO_SVC                                      (0xf7)
#define CS40L30_SYM_SVC_MSG_SVC_TO_HAPTICS                                      (0xf8)
#define CS40L30_SYM_SVC_SVC_SEQ_TYPE                                            (0xf9)
#define CS40L30_SYM_SVC_SVC_MODE_CONTROL                                        (0xfa)
#define CS40L30_SYM_SVC_SVC_TIMESTAMP                                           (0xfb)
#define CS40L30_SYM_SVC_SVC_STATE_MACHINE_STATUS                                (0xfc)
#define CS40L30_SYM_SVC_SVC_NADA_COUNTER                                        (0xfd)
#define CS40L30_SYM_SVC_SVC_INIT_COUNTER                                        (0xfe)
#define CS40L30_SYM_SVC_SVC_PLAYBACK_STARTUP_COUNTER                            (0xff)
#define CS40L30_SYM_SVC_SVC_PLAYBACK_TRACKING_COUNTER                           (0x100)
#define CS40L30_SYM_SVC_SVC_PLAYBACK_DONE_COUNTER                               (0x101)
#define CS40L30_SYM_SVC_SVC_MUTE_COUNTER                                        (0x102)
#define CS40L30_SYM_SVC_INIT_START_COUNTER                                      (0x103)
#define CS40L30_SYM_SVC_PBK_START_COUNTER                                       (0x104)
#define CS40L30_SYM_SVC_PBK_RESUME_COUNTER                                      (0x105)
#define CS40L30_SYM_SVC_PBK_BRAKE_COUNTER                                       (0x106)
#define CS40L30_SYM_SVC_PBK_STOP_COUNTER                                        (0x107)
#define CS40L30_SYM_SVC_INIT_DONE_COUNTER                                       (0x108)
#define CS40L30_SYM_SVC_PBK_DONE_COUNTER                                        (0x109)
#define CS40L30_SYM_SVC_MUTED_COUNTER                                           (0x10a)
#define CS40L30_SYM_SVC_ERROR_COUNTER                                           (0x10b)
#define CS40L30_SYM_SVC_THERMO_ENABLE                                           (0x10c)
#define CS40L30_SYM_SVC_DEC_LP_SOS1_B0                                          (0x10d)
#define CS40L30_SYM_SVC_DEC_LP_SOS1_B1                                          (0x10e)
#define CS40L30_SYM_SVC_DEC_LP_SOS1_B2                                          (0x10f)
#define CS40L30_SYM_SVC_DEC_LP_SOS1_A1                                          (0x110)
#define CS40L30_SYM_SVC_DEC_LP_SOS1_A2                                          (0x111)
#define CS40L30_SYM_SVC_MDL_LP_SOS2_B0                                          (0x112)
#define CS40L30_SYM_SVC_MDL_LP_SOS2_B1                                          (0x113)
#define CS40L30_SYM_SVC_MDL_LP_SOS2_B2                                          (0x114)
#define CS40L30_SYM_SVC_MDL_LP_SOS2_A1                                          (0x115)
#define CS40L30_SYM_SVC_MDL_LP_SOS2_A2                                          (0x116)
#define CS40L30_SYM_SVC_THERMO_RE0                                              (0x117)
#define CS40L30_SYM_SVC_THERMO_A11                                              (0x118)
#define CS40L30_SYM_SVC_THERMO_A12                                              (0x119)
#define CS40L30_SYM_SVC_THERMO_A21                                              (0x11a)
#define CS40L30_SYM_SVC_THERMO_A22                                              (0x11b)
#define CS40L30_SYM_SVC_THERMO_B11                                              (0x11c)
#define CS40L30_SYM_SVC_THERMO_W1                                               (0x11d)
#define CS40L30_SYM_SVC_THERMO_W2                                               (0x11e)
#define CS40L30_SYM_SVC_THERMO_R1                                               (0x11f)
#define CS40L30_SYM_SVC_THERMO_R2                                               (0x120)
#define CS40L30_SYM_SVC_THERMO_R3                                               (0x121)
#define CS40L30_SYM_SVC_THERMO_R4                                               (0x122)
#define CS40L30_SYM_SVC_THERMO_DEC                                              (0x123)
#define CS40L30_SYM_SVC_THERMO_TIMESTAMP                                        (0x124)
#define CS40L30_SYM_SVC_LE_CANCEL_SF                                            (0x125)
#define CS40L30_SYM_SVC_RA_SMOOTHING_FACTOR                                     (0x126)
#define CS40L30_SYM_SVC_THERMO_VMON_X_IMON_FS                                   (0x127)
#define CS40L30_SYM_SVC_ID_UNSTABLE                                             (0x128)
#define CS40L30_SYM_SVC_ID_ACPOW_COEFF                                          (0x129)
#define CS40L30_SYM_SVC_ID_DCNOTCH_COEF                                         (0x12a)
#define CS40L30_SYM_SVC_ID_DC_HOLDOFF                                           (0x12b)
#define CS40L30_SYM_SVC_ID_HAP_DLY                                              (0x12c)
#define CS40L30_SYM_SVC_ID_ENABLE                                               (0x12d)
#define CS40L30_SYM_SVC_ID_VMONPOW                                              (0x12e)
#define CS40L30_SYM_SVC_ID_HMONPOW                                              (0x12f)
#define CS40L30_SYM_SVC_ID_HINPOW                                               (0x130)
#define CS40L30_SYM_SVC_ID_FRECP                                                (0x131)
#define CS40L30_SYM_SVC_ID_VP_COEF                                              (0x132)
#define CS40L30_SYM_SVC_ID_HP_COEF                                              (0x133)
#define CS40L30_SYM_SVC_ID_FRECPTHR                                             (0x134)
#define CS40L30_SYM_SVC_ID_UNSTABLE_FLAG                                        (0x135)
#define CS40L30_SYM_SVC_ID_STABLE_TH                                            (0x136)
#define CS40L30_SYM_SVC_ID_UNSTABLE_TH                                          (0x137)
#define CS40L30_SYM_SVC_ID_ANGLEMETRIC_COEFF                                    (0x138)
#define CS40L30_SYM_SVC_ID_RE_SAFE_VAL                                          (0x139)
#define CS40L30_SYM_SVC_ID_CONTROL_ENABLE                                       (0x13a)
#define CS40L30_SYM_SVC_ID_VALID_POW_TH                                         (0x13b)
#define CS40L30_SYM_SVC_ID_SVC_SHUTDOWN_VAL                                     (0x13c)
#define CS40L30_SYM_SVC_ID_SVC_SHUTDOWN_STATE                                   (0x13d)
#define CS40L30_SYM_SVC_ID_SHUTDOWN_COEFF                                       (0x13e)
#define CS40L30_SYM_SVC_ID_SVC_SHUTDOWN                                         (0x13f)
#define CS40L30_SYM_SVC_ID_SVC_SHUTDOWN_RESET                                   (0x140)
#define CS40L30_SYM_SVC_ID_SVC_SHUTDOWN_TH                                      (0x141)
#define CS40L30_SYM_SVC_ID_LOCKCOUNT_INIT                                       (0x142)
#define CS40L30_SYM_SVC_ID_EVENT_LOCKCOUNT                                      (0x143)
#define CS40L30_SYM_SVC_ID_HMONOFF_THR                                          (0x144)
#define CS40L30_SYM_SVC_ID_VMONOK_THR                                           (0x145)
#define CS40L30_SYM_SVC_ID_HMONOFF_FLAG                                         (0x146)
#define CS40L30_SYM_SVC_HW_LPF2_BYPASS                                          (0x147)
#define CS40L30_SYM_SVC_HW_LPF1_BYPASS                                          (0x148)
#define CS40L30_SYM_SVC_HW_I_SRC                                                (0x149)
#define CS40L30_SYM_SVC_HW_LPF2_BW_SEL                                          (0x14a)
#define CS40L30_SYM_SVC_HW_LPF1_BW_SEL                                          (0x14b)
#define CS40L30_SYM_SVC_HW_HPF_BW_SEL                                           (0x14c)
#define CS40L30_SYM_SVC_HW_SER_R_EN                                             (0x14d)
#define CS40L30_SYM_SVC_HW_SER_L_EN                                             (0x14e)
#define CS40L30_SYM_SVC_HW_SER_C_EN                                             (0x14f)
#define CS40L30_SYM_SVC_HW_PAR_RLC_EN                                           (0x150)
#define CS40L30_SYM_SVC_HW_SER_R_CTRL                                           (0x151)
#define CS40L30_SYM_SVC_HW_SER_L_CTRL                                           (0x152)
#define CS40L30_SYM_SVC_HW_SER_C_CTRL                                           (0x153)
#define CS40L30_SYM_SVC_HW_PAR_RLC_SF                                           (0x154)
#define CS40L30_SYM_SVC_HW_PAR_RLC_C1                                           (0x155)
#define CS40L30_SYM_SVC_HW_PAR_RLC_C2                                           (0x156)
#define CS40L30_SYM_SVC_HW_PAR_RLC_B1                                           (0x157)
#define CS40L30_SYM_SVC_HW_GAIN_MAN                                             (0x158)
#define CS40L30_SYM_SVC_HW_GAIN_EXP                                             (0x159)
#define CS40L30_SYM_SVC_INIT_PH_PILOT_HI_PERIOD_SMP                             (0x15a)
#define CS40L30_SYM_SVC_INIT_PH_PILOT_HI_LEVEL                                  (0x15b)
#define CS40L30_SYM_SVC_INIT_PH_PILOT_HI_START_SMP                              (0x15c)
#define CS40L30_SYM_SVC_INIT_PH_OFST_CAL_NSMP                                   (0x15d)
#define CS40L30_SYM_SVC_INIT_PH_OFST_CAL_INVERSE_NSMP                           (0x15e)
#define CS40L30_SYM_SVC_INIT_PH_OFST_CAL_START_SMP                              (0x15f)
#define CS40L30_SYM_SVC_INIT_PH_OFST_STL_NSMP                                   (0x160)
#define CS40L30_SYM_SVC_RE_MIN                                                  (0x161)
#define CS40L30_SYM_SVC_RE_MAX                                                  (0x162)
#define CS40L30_SYM_SVC_LE_MIN                                                  (0x163)
#define CS40L30_SYM_SVC_LE_MAX                                                  (0x164)
#define CS40L30_SYM_SVC_THERM_DECIMX                                            (0x165)
#define CS40L30_SYM_SVC_SWITCH_R_LPF_BW_SMP                                     (0x166)
#define CS40L30_SYM_SVC_R_LPF_BW_SEL_HIGH                                       (0x167)
#define CS40L30_SYM_SVC_R_LPF_BW_SEL_LOW                                        (0x168)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_RU_STEP                                    (0x169)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_RD_STEP                                    (0x16a)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_HI_PERIOD_SMP                              (0x16b)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_HI_LEVEL                                   (0x16c)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_HI_START_SMP                               (0x16d)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_LO_PERIOD_SMP                              (0x16e)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_LO_LEVEL                                   (0x16f)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_LO_START_SMP                               (0x170)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EST_HI_ACC_START_SMP                      (0x171)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EST_HI_LSFIT_NUM                          (0x172)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EST_LO_ACC_START_SMP                      (0x173)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EST_LO_LSFIT_NUM                          (0x174)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EL_HI_LSFIT_INCRN_SMP                     (0x175)
#define CS40L30_SYM_SVC_PBK_PH_TRK_RL_EL_HI_LSFIT_INCRN_SMP                     (0x176)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EL_HI_LSFIT_INCR1_SMP                     (0x177)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EL_LO_LSFIT_INCRN_SMP                     (0x178)
#define CS40L30_SYM_SVC_PBK_PH_TRK_RL_EL_LO_LSFIT_INCRN_SMP                     (0x179)
#define CS40L30_SYM_SVC_PBK_PH_ACQ_RL_EL_LO_LSFIT_INCR1_SMP                     (0x17a)
#define CS40L30_SYM_SVC_PBK_PILOT_HI_2_LO_SWITCH_SMP                            (0x17b)
#define CS40L30_SYM_SVC_PBK_R_EST_HI_2_LO_SWITCH_SMP                            (0x17c)
#define CS40L30_SYM_SVC_CAT_PILOT_LO_PERIOD_SMP                                 (0x17d)
#define CS40L30_SYM_SVC_CAT_PILOT_LO_LEVEL                                      (0x17e)
#define CS40L30_SYM_SVC_CAT_PILOT_LO_START_SMP                                  (0x17f)
#define CS40L30_SYM_SVC_CAT_OFST_CAL_NSMP                                       (0x180)
#define CS40L30_SYM_SVC_CAT_OFST_CAL_INVERSE_NSMP                               (0x181)
#define CS40L30_SYM_SVC_CAT_OFST_CAL_START_SMP                                  (0x182)
#define CS40L30_SYM_SVC_CAT_OFST_STL_NSMP                                       (0x183)
#define CS40L30_SYM_SVC_WAVFRM_LIM_LVL                                          (0x184)
#define CS40L30_SYM_SVC_WAVFRM_NRM_LVL                                          (0x185)
#define CS40L30_SYM_SVC_WAVFRM_RU_RATE                                          (0x186)
#define CS40L30_SYM_SVC_WAVFRM_RD_RATE                                          (0x187)
#define CS40L30_SYM_SVC_INSTABILITY_REQ_WFRM_LIMIT                              (0x188)
#define CS40L30_SYM_SVC_INSTABILITY_REQ_LOWER_SER_R                             (0x189)
#define CS40L30_SYM_SVC_INSTABILITY_TIMEOUT_SMP                                 (0x18a)
#define CS40L30_SYM_SVC_MUTE_PH_PILOT_RD_STEP                                   (0x18b)
#define CS40L30_SYM_SVC_DEBUG_ME                                                (0x18c)
#define CS40L30_SYM_SVC_FIX24_LO_DEBUG_ME                                       (0x18d)
#define CS40L30_SYM_SVC_FIX24_HI_DEBUG_ME                                       (0x18e)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_HI_LEVEL_CL2OL                             (0x18f)
#define CS40L30_SYM_SVC_PBK_PH_PILOT_LO_LEVEL_CL2OL                             (0x190)
#define CS40L30_SYM_SVC_CAT_EVENT_TIMESTAMP_IN_MILLISECONDS                     (0x191)
#define CS40L30_SYM_SVC_FORCE_RE_INIT_WHEN_NO_HIBERNATE                         (0x192)
#define CS40L30_SYM_SVC_IMON_OFFSET_TRIM_SF                                     (0x193)
#define CS40L30_SYM_SVC_IMON_OFFSET_TRIM_ISF                                    (0x194)
#define CS40L30_SYM_SVC_IMON_OFFSET_OTP_VAL                                     (0x195)
#define CS40L30_SYM_SVC_HW_SVC_CTRL                                             (0x196)
#define CS40L30_SYM_SVC_HW_SVC_FILT_CFG                                         (0x197)
#define CS40L30_SYM_SVC_HW_SVC_GAIN                                             (0x198)

/** @} */

/**********************************************************************************************************************/
#ifdef __cplusplus
}
#endif

#endif // CS40L30_SYM_H

